### PR TITLE
Upgrade to Python3

### PR DESCRIPTION
**Pull request by pravirkr**
changes:

- File class modified
- bytes/string encoding in the header params
- Changed %-formatting to f-Strings
- Need Python 3.6 or later

### CODE REVIEW

**Comment by ewanbarr** [comment]
Wow, this is quite a big change and one that people have been asking for a while, thanks. However, I am concerned that merging these changes would have the effect of breaking a large amount of legacy code. In particular Docker builds that rely on pulling the SigPyProc master branch. The way I see it there are two choices here, either python3 support is maintained in a dedicated branch (which is not ideal as it will never be remerged) or you take this code and create a new repository called sigpyproc3 and we add a link to that repo in the README from this one. 

The end game here would be that people eventually move away from sigpyproc to sigpyproc3.

I am open to other suggestions.

**Comment by pravirkr** [comment]
Hi Ewan,

yeah, maintaining a different branch might not be the ideal choice here. Also, I have several PRs in the process (PSRFits support, cmd-line and visualization utilities, and maybe FRB simulator/injection support). 

So, for the time being, I will proceed with a new repo (sigpyproc3) and try to expand it further.

Thanks,
Pravir

**Comment by ewanbarr** [comment]
Hi Pravir,

Sounds sensible. Can you send me the link to the new repo.

Cheers,
Ewan

**Comment by pravirkr** [comment]
The new repo is here:
https://github.com/pravirkr/sigpyproc3

**Pull request closed without merging**
